using System.Collections.Generic;

namespace learning_siltums_1.HardcodedData
{
    public class HardcodedData
    {
        public static List<QuestionAndAnswers> GetQnAList()
        {
            var res = new List<QuestionAndAnswers>()
            {
                new QuestionAndAnswers(){ QuestionId = 1, Question = "Kas ir izolēta termodinamiska sistēma", Answer="Par izolētu sauc tādu termodinamisko sistēmu, kurai nav mijiedarbības ar apkārtējo vidi.", AnswerImage="", Points = 1 },
                new QuestionAndAnswers(){ QuestionId = 2, Question = "Kas ir neizolēta termodinamiska sistēma", Answer="Par neizolētu sauc tādu termodinamisko sistēmu, kas mijiedarbojas ar apkārtējo vidi.", AnswerImage="", Points = 1 },
                new QuestionAndAnswers(){ QuestionId = 3, Question = "Kas ir noslēgta termodinamiska sistēma", Answer="Ja mijiedarbības rezultātā ar apkārtējo vidi termodinamiskās sistēmas ķermeņu skaits, t.i., sistēmas lielums (masa), nemainās, sistēmu sauc par noslēgtu.", AnswerImage="", Points = 1 },
                new QuestionAndAnswers(){ QuestionId = 4, Question = "Kas ir vaļēja termodinamiska sistēma", Answer="Ja mijiedarbības rezultātā ar apkārtējo vidi termodinamiskās sistēmas ķermeņu skaits, t.i., sistēmas lielums (masa), mainās, sistēmu sauc par nenoslēgtu jeb vaļēju.", AnswerImage="", Points = 1 },
                new QuestionAndAnswers(){ QuestionId = 5, Question = "Ko raksturo ķermeņa temperatūra", Answer="Temperatūra raksturo termodinamiskās sistēmas un tās sastāvdaļu siltuma pakāpi.", AnswerImage="", Points = 1 },
                new QuestionAndAnswers(){ QuestionId = 6, Question = "Uzrakstīt skaitlisko sakarību starp absolūto un Celsija skalas temperatūru", Answer="1K = 1C; T=t+273.15 C", AnswerImage="", Points = 1 },
                new QuestionAndAnswers(){ QuestionId = 7, Question = "Definēt spiedienu", Answer="Spiediens ir spēks, ar kādu darba ķermenis iedarbojas uz virsmas laukuma vienību", AnswerImage="", Points = 1 },
                new QuestionAndAnswers(){ QuestionId = 8, Question = "Kādas ir spiediena mērvienības SI un citās sistēmās", Answer="N/m^2 jeb Pa (paskāls). Normālā fiziskā atmosfēra (bar?), tehniskā atmosfēra (at), mm H2O staba, mm Hg staba", AnswerImage="", Points = 1 },
                new QuestionAndAnswers(){ QuestionId = 9, Question = "Kas ir īpatnējais tilpums, tā mērvienība", Answer="Īpatnējais tilpums ir darba vielas viena masas kilograma ieņemtais tilpums, ko pieņemts apzīmēt ar v. v=V/M, kur V - darba vielas kopējais tilpums (m^3), M - darba vielas masa (kg).", AnswerImage="", Points = 1 },
                new QuestionAndAnswers(){ QuestionId = 10, Question = "Kas ir darba ķermeņa normālie apstākļi", Answer="T=273.15K jeb t=0C; spiediens p=101325 Pa jeb 1 fizikālā atmosfēra (bar).", AnswerImage="", Points = 1 },
                new QuestionAndAnswers(){ QuestionId = 11, Question = "Kas ir entalpija, tās mērvienība", Answer="Termodinamiskās sistēmas iekšējās enerģijas un tilpuma enerģijas summa. Entalpiju apzīmē ar h, mērvienība J/kg vai kJ/kg.", AnswerImage="", Points = 1 },
                new QuestionAndAnswers(){ QuestionId = 12, Question = "Kāda ir entropijas mērvienība", Answer="J/K vai kJ/K", AnswerImage="", Points = 1 },
                new QuestionAndAnswers(){ QuestionId = 13, Question = "Kas ir termodinamiskais process", Answer="", AnswerImage="", Points = 1 },
                new QuestionAndAnswers(){ QuestionId = 14, Question = "Kas ir ideāla gāze", Answer="", AnswerImage="", Points = 1 },
                new QuestionAndAnswers(){ QuestionId = 15, Question = "Uzrakstīt gāzes stāvokļa vienādojumu ideālai gāzei", Answer="", AnswerImage="", Points = 1 },
                new QuestionAndAnswers(){ QuestionId = 16, Question = "Kas ir gāzes individuālā konstante, mērvienība", Answer="", AnswerImage="", Points = 1 },
                new QuestionAndAnswers(){ QuestionId = 17, Question = "Kas ir īpatnējā siltumietilpība, mērvienība", Answer="", AnswerImage="", Points = 1 },
                new QuestionAndAnswers(){ QuestionId = 18, Question = "Kādi ir īpatnējās siltumietilpības veidi, mērvienības", Answer="", AnswerImage="", Points = 1 },
                new QuestionAndAnswers(){ QuestionId = 19, Question = "Pirmais termodinamikas likums", Answer="", AnswerImage="", Points = 1 },
                new QuestionAndAnswers(){ QuestionId = 20, Question = "Nosaukt termodinamikas pamatprocesus", Answer="", AnswerImage="", Points = 1 },
                new QuestionAndAnswers(){ QuestionId = 21, Question = "Kas ir termodinamiskais cikls", Answer="", AnswerImage="", Points = 1 },
                new QuestionAndAnswers(){ QuestionId = 22, Question = "Uzzīmēt Karno ciklu p-v koordinātu sistēmā. Paskaidrot līknes", Answer="", AnswerImage="", Points = 1 },
                new QuestionAndAnswers(){ QuestionId = 23, Question = "Kā izsaka Karno cikla lietderības koeficientu", Answer="", AnswerImage="", Points = 1 },
                new QuestionAndAnswers(){ QuestionId = 24, Question = "Uzrakstīt kādu no otrā termodinamikas likuma formulējumiem", Answer="", AnswerImage="", Points = 1 },
                new QuestionAndAnswers(){ QuestionId = 25, Question = "Kas ir ekserģija", Answer="", AnswerImage="", Points = 1 },
                new QuestionAndAnswers(){ QuestionId = 26, Question = "Ar ko atšķiras reāla gāze no ideālas", Answer="", AnswerImage="", Points = 1 },
                new QuestionAndAnswers(){ QuestionId = 27, Question = "Uzrakstīt Van der Vālsa vienādojumu reālai gāzei un paskaidrot tā locekļus", Answer="", AnswerImage="", Points = 1 },
                new QuestionAndAnswers(){ QuestionId = 28, Question = "Kas ir ūdens trīskāršais punkts", Answer="", AnswerImage="", Points = 1 },
                new QuestionAndAnswers(){ QuestionId = 29, Question = "Kas ir pārkarsēts tvaiks", Answer="", AnswerImage="", Points = 1 },
                new QuestionAndAnswers(){ QuestionId = 30, Question = "Kas ir mitrs tvaiks", Answer="", AnswerImage="", Points = 1 },
                new QuestionAndAnswers(){ QuestionId = 31, Question = "Kas ir sauss piesātināts tvaiks", Answer="", AnswerImage="", Points = 1 },
                new QuestionAndAnswers(){ QuestionId = 32, Question = "Kādai vielas fāzei piemīt īpatnējie tilpumi, ko apzīmē ar: v’, v’’, v, vx", Answer="", AnswerImage="", Points = 1 },
                new QuestionAndAnswers(){ QuestionId = 33, Question = "Kas ir ūdens iztvaikošanas siltums", Answer="", AnswerImage="", Points = 1 },
                new QuestionAndAnswers(){ QuestionId = 34, Question = "Kas veido ūdens iztvaikošanas siltumu", Answer="", AnswerImage="", Points = 1 },
                new QuestionAndAnswers(){ QuestionId = 35, Question = "Kāds ir un kam ir proporcionāls darbs un iekšējās enerģijas izmaiņa tvaikam izohoriskā procesā", Answer="", AnswerImage="", Points = 1 },
                new QuestionAndAnswers(){ QuestionId = 36, Question = "Kāds ir un kam ir proporcionāls darbs un iekšējās enerģijas izmaiņa tvaikam adiabātiskā procesā", Answer="", AnswerImage="", Points = 1 },
                new QuestionAndAnswers(){ QuestionId = 37, Question = "Kas ir rasas punkts mitram gaisam", Answer="", AnswerImage="", Points = 1 },
                new QuestionAndAnswers(){ QuestionId = 38, Question = "Kas ir gaisa relatīvais mitrums, mērvienība", Answer="", AnswerImage="", Points = 1 },
                new QuestionAndAnswers(){ QuestionId = 39, Question = "Kas ir gaisa absolūtais mitrums, mērvienība", Answer="", AnswerImage="", Points = 1 },
                new QuestionAndAnswers(){ QuestionId = 40, Question = "Kas ir gaisa mitruma saturs, mērvienība", Answer="", AnswerImage="", Points = 1 },
                new QuestionAndAnswers(){ QuestionId = 41, Question = "Ko sauc par gāzi tvaika-gāzes maisījumā", Answer="", AnswerImage="", Points = 1 },
                new QuestionAndAnswers(){ QuestionId = 42, Question = "Ko sauc par tvaiku tvaika-gāzes maisījumā", Answer="", AnswerImage="", Points = 1 },
                new QuestionAndAnswers(){ QuestionId = 43, Question = "Uzzīmēt kompresora ideālo ciklu, paskaidrot līknes", Answer="", AnswerImage="", Points = 2 },
                new QuestionAndAnswers(){ QuestionId = 44, Question = "Uzzīmēt iekšdedzes motora Otto ciklu p-v koordinātu sistēmā, paskaidrot līknes", Answer="", AnswerImage="", Points = 2 },
                new QuestionAndAnswers(){ QuestionId = 45, Question = "Uzzīmēt iekšdedzes motora Dīzeļa ciklu p-v koordinātu sistēmā, paskaidrot līknes", Answer="", AnswerImage="", Points = 2 },
                new QuestionAndAnswers(){ QuestionId = 46, Question = "Uzzīmēt gāzes turbīnas ciklu p-v koordinātu sistēmā un paskaidrot līknes", Answer="", AnswerImage="", Points = 2 },
                new QuestionAndAnswers(){ QuestionId = 47, Question = "Uzzīmēt pamatcikla tvaika iekārtas shēmu, nosaukt tās sastāvdaļas", Answer="", AnswerImage="", Points = 2 },
                new QuestionAndAnswers(){ QuestionId = 48, Question = "Uzzīmēt tvaika iekārtas pamatciklu T-s koordinātu sistēmā, paskaidrot līknes", Answer="", AnswerImage="", Points = 2 },
                new QuestionAndAnswers(){ QuestionId = 49, Question = "Uzzīmēt tvaika iekārtas ciklu ar atkārtotu tvaika pārkarsēšanu T-s koordinātu sistēmā, paskaidrot līknes", Answer="", AnswerImage="", Points = 2 },
                new QuestionAndAnswers(){ QuestionId = 50, Question = "Uzzīmēt saldēšanas iekārtas ideālo ciklu T-s koordinātu sistēmā, paskaidrot līknes", Answer="", AnswerImage="", Points = 2 },
                new QuestionAndAnswers(){ QuestionId = 51, Question = "Uzzīmēt gāzes cikla saldēšanas iekārtas shēmu, nosaukt sastāvdaļas", Answer="", AnswerImage="", Points = 2 },
                new QuestionAndAnswers(){ QuestionId = 52, Question = "Uzzīmēt saldēšanas iekārtas gāzes ciklu T-s koordinātu sistēmā, paskaidrot līknes", Answer="", AnswerImage="", Points = 2 },
                new QuestionAndAnswers(){ QuestionId = 53, Question = "Uzzīmēt tvaika cikla saldēšanas iekārtas shēmu, nosaukt sastāvdaļas", Answer="", AnswerImage="", Points = 2 },
                new QuestionAndAnswers(){ QuestionId = 54, Question = "Uzzīmēt saldēšanas iekārtas tvaika ciklu T-s koordinātu sistēmā, paskaidrot līknes", Answer="", AnswerImage="", Points = 2 },
                new QuestionAndAnswers(){ QuestionId = 55, Question = "Paskaidrot saldēšanas iekārtas termodinamiskos darbības principus", Answer="", AnswerImage="", Points = 2 },
                new QuestionAndAnswers(){ QuestionId = 56, Question = "Uzzīmēt siltumsūkņa shēmu, nosaukt sastāvdaļas", Answer="", AnswerImage="", Points = 2 },
                new QuestionAndAnswers(){ QuestionId = 57, Question = "Paskaidrot siltumsūkņa termodinamiskos darbības principus", Answer="", AnswerImage="", Points = 2 },
                new QuestionAndAnswers(){ QuestionId = 58, Question = "Kas ir siltumapmaiņa", Answer="", AnswerImage="", Points = 1 },
                new QuestionAndAnswers(){ QuestionId = 59, Question = "Kādos veidos notiek siltumapmaiņa", Answer="", AnswerImage="", Points = 1 },
                new QuestionAndAnswers(){ QuestionId = 60, Question = "Kā tiek pārnesta siltuma enerģija vadīšanā", Answer="", AnswerImage="", Points = 1 },
                new QuestionAndAnswers(){ QuestionId = 61, Question = "Kā tiek pārnesta siltuma enerģija konvekcijā", Answer="", AnswerImage="", Points = 1 },
                new QuestionAndAnswers(){ QuestionId = 62, Question = "Kā tiek pārnesta siltuma enerģija starošanā", Answer="", AnswerImage="", Points = 1 },
                new QuestionAndAnswers(){ QuestionId = 63, Question = "Kas ir temperatūras lauks", Answer="", AnswerImage="", Points = 1 },
                new QuestionAndAnswers(){ QuestionId = 64, Question = "Kas ir stacionārs un nestacionārs temperatūras lauks", Answer="", AnswerImage="", Points = 1 },
                new QuestionAndAnswers(){ QuestionId = 65, Question = "Ko raksturo temperatūras gradients", Answer="", AnswerImage="", Points = 1 },
                new QuestionAndAnswers(){ QuestionId = 66, Question = "Kas ir siltumvadītspējas koeficients", Answer="", AnswerImage="", Points = 1 },
                new QuestionAndAnswers(){ QuestionId = 67, Question = "Uzskaitīt sistēmu viennozīmīguma nosacījumus", Answer="", AnswerImage="", Points = 1 },
                new QuestionAndAnswers(){ QuestionId = 68, Question = "Uzrakstīt Ņūtona vienādojumu siltuma plūsmas aprēķinam", Answer="", AnswerImage="", Points = 1 },
                new QuestionAndAnswers(){ QuestionId = 69, Question = "Kas ir siltumatdeves koeficients", Answer="", AnswerImage="", Points = 1 },
                new QuestionAndAnswers(){ QuestionId = 70, Question = "Uzzīmēt temperatūras sadalījumu siltumam plūstot caur plāksni pie trešās kārtas robežnosacījumiem", Answer="", AnswerImage="", Points = 1 },
                new QuestionAndAnswers(){ QuestionId = 71, Question = "Kā var aprēķināt siltumpārejas koeficientu daudzslāņu plāksnei", Answer="", AnswerImage="", Points = 1 },
                new QuestionAndAnswers(){ QuestionId = 72, Question = "Uzzīmēt temperatūras sadalījumu siltumam plūstot caur cilindriskas caurules sienu pie trešās kārtas robežnosacījumiem", Answer="", AnswerImage="", Points = 1 },
                new QuestionAndAnswers(){ QuestionId = 73, Question = "Kas ir cauruļvadu siltumizolācijas kritiskais biezums", Answer="", AnswerImage="", Points = 1 },
                new QuestionAndAnswers(){ QuestionId = 74, Question = "Kas ir apribojuma koeficients", Answer="", AnswerImage="", Points = 1 },
                new QuestionAndAnswers(){ QuestionId = 75, Question = "Uzzīmēt temperatūras sadalījuma līkni ķermenī virsmas tuvumā tam dziestot no vienas puses", Answer="", AnswerImage="", Points = 1 },
                new QuestionAndAnswers(){ QuestionId = 76, Question = "Uzzīmēt temperatūras sadalījuma līkni plāksnē tai dziestot no abām pusēm", Answer="", AnswerImage="", Points = 1 },
                new QuestionAndAnswers(){ QuestionId = 77, Question = "Kāda ir līdzības skaitļu būtība", Answer="", AnswerImage="", Points = 1 },
                new QuestionAndAnswers(){ QuestionId = 78, Question = "Kas ir brīvā konvekcija", Answer="", AnswerImage="", Points = 1 },
                new QuestionAndAnswers(){ QuestionId = 79, Question = "Kas ir piespiedu konvekcija", Answer="", AnswerImage="", Points = 1 },
                new QuestionAndAnswers(){ QuestionId = 80, Question = "Izskaidrot, kā notiek siltumpārnese laminārā plūsmā", Answer="", AnswerImage="", Points = 1 },
                new QuestionAndAnswers(){ QuestionId = 81, Question = "Izskaidrot, kā notiek siltumpārnese turbulentā plūsmā", Answer="", AnswerImage="", Points = 1 },
                new QuestionAndAnswers(){ QuestionId = 82, Question = "Uzzīmēt siltumatdeves koeficienta izmaiņas grafiku atkarībā no augstuma brīvai konvekcijai gar vertikālu sienu", Answer="", AnswerImage="", Points = 1 },
                new QuestionAndAnswers(){ QuestionId = 83, Question = "Kas ir kodolveida kondensācija", Answer="", AnswerImage="", Points = 1 },
                new QuestionAndAnswers(){ QuestionId = 84, Question = "Kas ir plēves veida kondensācija", Answer="", AnswerImage="", Points = 1 },
                new QuestionAndAnswers(){ QuestionId = 85, Question = "Kas ir kodolveida iztvaikošana", Answer="", AnswerImage="", Points = 1 },
                new QuestionAndAnswers(){ QuestionId = 86, Question = "Kas ir plēves veida iztvaikošana", Answer="", AnswerImage="", Points = 1 },
                new QuestionAndAnswers(){ QuestionId = 87, Question = "Cik ir A, R, D absolūti melnam ķermenim", Answer="", AnswerImage="", Points = 1 },
                new QuestionAndAnswers(){ QuestionId = 88, Question = "Cik ir A, R, D absolūti caurspīdīgam ķermenim", Answer="", AnswerImage="", Points = 1 },
                new QuestionAndAnswers(){ QuestionId = 89, Question = "Cik ir A, R, D absolūti baltam ķermenim", Answer="", AnswerImage="", Points = 1 },
                new QuestionAndAnswers(){ QuestionId = 90, Question = "Kas ir integrālais starojums", Answer="", AnswerImage="", Points = 1 },
                new QuestionAndAnswers(){ QuestionId = 91, Question = "Kas ir monohromatiskais starojums", Answer="", AnswerImage="", Points = 1 },
                new QuestionAndAnswers(){ QuestionId = 92, Question = "Kas ir starojuma plūsmas blīvums (intensitāte)", Answer="", AnswerImage="", Points = 1 },
                new QuestionAndAnswers(){ QuestionId = 93, Question = "Paskaidrot Planka likuma būtību siltumstarošanā", Answer="", AnswerImage="", Points = 1 },
                new QuestionAndAnswers(){ QuestionId = 94, Question = "Paskaidrot Vjēna likuma būtību siltumstarošanā", Answer="", AnswerImage="", Points = 1 },
                new QuestionAndAnswers(){ QuestionId = 95, Question = "Paskaidrot Stefana-Bolcmaņa likuma būtību siltumstarošanā", Answer="", AnswerImage="", Points = 1 },
                new QuestionAndAnswers(){ QuestionId = 96, Question = "Paskaidrot otrā Kirhofa likuma būtību siltumstarošanā", Answer="", AnswerImage="", Points = 1 },
                new QuestionAndAnswers(){ QuestionId = 97, Question = "Paskaidrot Lamberta likuma būtību siltumstarošanā", Answer="", AnswerImage="", Points = 1 },
                new QuestionAndAnswers(){ QuestionId = 98, Question = "Uzzīmēt skici, kas paskaidro ķermeņu savstarpējo apstarošanos", Answer="", AnswerImage="", Points = 1 },
            };

            return res;
        }
    }
}